name: Full Stack Deployment

on:
  push:
    branches:
      - Dev

jobs:
  deploy-dotnet:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Solution
        run: dotnet restore DynamicDFSAPI/iProofProcessDFSService.sln

      - name: Build Solution
        run: dotnet build DynamicDFSAPI/iProofProcessDFSService.sln --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish DynamicDFSAPI/iProofProcessService/iProofProcessService.csproj -c Release -o publish

      - name: Ensure Target Directory Exists
        run: mkdir -p /home/Share/Presentations/${{ github.event.repository.name }}API

      - name: Stop Service
        run: sudo systemctl stop ${{ github.event.repository.name }}API.service || true

      - name: Clean Old Files
        run: rm -rf /home/Share/Presentations/${{ github.event.repository.name }}API/*

      - name: Copy New Files
        run: cp -r publish/* /home/Share/Presentations/${{ github.event.repository.name }}API/

      - name: Start Service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start ${{ github.event.repository.name }}API.service

  deploy-react:
    runs-on: [self-hosted, linux]
    needs: deploy-dotnet

    steps:
      - uses: actions/checkout@v4

      - name: Clean Node Modules
        working-directory: Client
        run: |
          rm -rf node_modules
          npm cache clean --force
      
      - name: Install Dependencies
        working-directory: Client
        run: npm install

      - name: Build React App
        working-directory: Client
        run: npm run build
        env:
	  NODE_OPTIONS: "--max-old-space-size=8192"
          CI: false
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_AUTH_URL: ${{ secrets.VITE_AUTH_URL }}
          VITE_DOCUMENT_SERVICE_URL: ${{ secrets.VITE_DOCUMENT_SERVICE_URL }}
          VITE_BASE_EXECUTION_URL: ${{ secrets.VITE_BASE_EXECUTION_URL }}
          VITE_INBOX_SETTING_ID: ${{ secrets.VITE_INBOX_SETTING_ID }}
          VITE_URL: ${{ secrets.VITE_URL }}

      - name: Ensure Target Directory Exists
        run: mkdir -p /home/Share/Presentations/${{ github.event.repository.name }}

      - name: Clean Old Build
        run: rm -rf /home/Share/Presentations/${{ github.event.repository.name }}/*

      - name: Copy Build Files
        run: cp -r Client/dist/* /home/Share/Presentations/${{ github.event.repository.name }}/
