name: Full Stack Deployment Trigger
on:
  push:
    branches:
      - Dev
jobs:
  deploy-dotnet:
    uses: ./.github/workflows/dotnet.yml
    secrets: inherit
  deploy-react:
    uses: ./.github/workflows/react.yml
    secrets: inherit
