name: Full Stack Deployment Trigger

on:
  push:
    branches:
      - Dev

jobs:
  deploy-dotnet:
    uses: ./.github/workflows/dotnet.yml

  deploy-react:
    uses: ./.github/workflows/react.yml
    secrets:
      VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
      VITE_AUTH_URL: ${{ secrets.VITE_AUTH_URL }}
      VITE_DOCUMENT_SERVICE_URL: ${{ secrets.VITE_DOCUMENT_SERVICE_URL }}
      VITE_BASE_EXECUTION_URL: ${{ secrets.VITE_BASE_EXECUTION_URL }}
      VITE_INBOX_SETTING_ID: ${{ secrets.VITE_INBOX_SETTING_ID }}
      VITE_URL: ${{ secrets.VITE_URL }}
